// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: fault.proto
// Protobuf Java Version: 4.29.0-rc1

public final class Fault {
  private Fault() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "-rc1",
      Fault.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface VehicleFaultDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VehicleFaultData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string device_no = 1;</code>
     * @return The deviceNo.
     */
    java.lang.String getDeviceNo();
    /**
     * <code>string device_no = 1;</code>
     * @return The bytes for deviceNo.
     */
    com.google.protobuf.ByteString
        getDeviceNoBytes();

    /**
     * <code>int32 fault_id = 2;</code>
     * @return The faultId.
     */
    int getFaultId();

    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     * @return Whether the timestamp field is set.
     */
    boolean hasTimestamp();
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     * @return The timestamp.
     */
    com.google.protobuf.Timestamp getTimestamp();
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     */
    com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

    /**
     * <code>.google.protobuf.Timestamp collected_at = 4;</code>
     * @return Whether the collectedAt field is set.
     */
    boolean hasCollectedAt();
    /**
     * <code>.google.protobuf.Timestamp collected_at = 4;</code>
     * @return The collectedAt.
     */
    com.google.protobuf.Timestamp getCollectedAt();
    /**
     * <code>.google.protobuf.Timestamp collected_at = 4;</code>
     */
    com.google.protobuf.TimestampOrBuilder getCollectedAtOrBuilder();

    /**
     * <code>.google.protobuf.Timestamp resolved_at = 5;</code>
     * @return Whether the resolvedAt field is set.
     */
    boolean hasResolvedAt();
    /**
     * <code>.google.protobuf.Timestamp resolved_at = 5;</code>
     * @return The resolvedAt.
     */
    com.google.protobuf.Timestamp getResolvedAt();
    /**
     * <code>.google.protobuf.Timestamp resolved_at = 5;</code>
     */
    com.google.protobuf.TimestampOrBuilder getResolvedAtOrBuilder();
  }
  /**
   * Protobuf type {@code VehicleFaultData}
   */
  public static final class VehicleFaultData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:VehicleFaultData)
      VehicleFaultDataOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 0,
        /* suffix= */ "-rc1",
        VehicleFaultData.class.getName());
    }
    // Use VehicleFaultData.newBuilder() to construct.
    private VehicleFaultData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private VehicleFaultData() {
      deviceNo_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Fault.internal_static_VehicleFaultData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Fault.internal_static_VehicleFaultData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Fault.VehicleFaultData.class, Fault.VehicleFaultData.Builder.class);
    }

    private int bitField0_;
    public static final int DEVICE_NO_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object deviceNo_ = "";
    /**
     * <code>string device_no = 1;</code>
     * @return The deviceNo.
     */
    @java.lang.Override
    public java.lang.String getDeviceNo() {
      java.lang.Object ref = deviceNo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceNo_ = s;
        return s;
      }
    }
    /**
     * <code>string device_no = 1;</code>
     * @return The bytes for deviceNo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeviceNoBytes() {
      java.lang.Object ref = deviceNo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FAULT_ID_FIELD_NUMBER = 2;
    private int faultId_ = 0;
    /**
     * <code>int32 fault_id = 2;</code>
     * @return The faultId.
     */
    @java.lang.Override
    public int getFaultId() {
      return faultId_;
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private com.google.protobuf.Timestamp timestamp_;
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     * @return Whether the timestamp field is set.
     */
    @java.lang.Override
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getTimestamp() {
      return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
    }

    public static final int COLLECTED_AT_FIELD_NUMBER = 4;
    private com.google.protobuf.Timestamp collectedAt_;
    /**
     * <code>.google.protobuf.Timestamp collected_at = 4;</code>
     * @return Whether the collectedAt field is set.
     */
    @java.lang.Override
    public boolean hasCollectedAt() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp collected_at = 4;</code>
     * @return The collectedAt.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getCollectedAt() {
      return collectedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : collectedAt_;
    }
    /**
     * <code>.google.protobuf.Timestamp collected_at = 4;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getCollectedAtOrBuilder() {
      return collectedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : collectedAt_;
    }

    public static final int RESOLVED_AT_FIELD_NUMBER = 5;
    private com.google.protobuf.Timestamp resolvedAt_;
    /**
     * <code>.google.protobuf.Timestamp resolved_at = 5;</code>
     * @return Whether the resolvedAt field is set.
     */
    @java.lang.Override
    public boolean hasResolvedAt() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp resolved_at = 5;</code>
     * @return The resolvedAt.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getResolvedAt() {
      return resolvedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : resolvedAt_;
    }
    /**
     * <code>.google.protobuf.Timestamp resolved_at = 5;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getResolvedAtOrBuilder() {
      return resolvedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : resolvedAt_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deviceNo_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, deviceNo_);
      }
      if (faultId_ != 0) {
        output.writeInt32(2, faultId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(3, getTimestamp());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(4, getCollectedAt());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeMessage(5, getResolvedAt());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deviceNo_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, deviceNo_);
      }
      if (faultId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, faultId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getTimestamp());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getCollectedAt());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getResolvedAt());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Fault.VehicleFaultData)) {
        return super.equals(obj);
      }
      Fault.VehicleFaultData other = (Fault.VehicleFaultData) obj;

      if (!getDeviceNo()
          .equals(other.getDeviceNo())) return false;
      if (getFaultId()
          != other.getFaultId()) return false;
      if (hasTimestamp() != other.hasTimestamp()) return false;
      if (hasTimestamp()) {
        if (!getTimestamp()
            .equals(other.getTimestamp())) return false;
      }
      if (hasCollectedAt() != other.hasCollectedAt()) return false;
      if (hasCollectedAt()) {
        if (!getCollectedAt()
            .equals(other.getCollectedAt())) return false;
      }
      if (hasResolvedAt() != other.hasResolvedAt()) return false;
      if (hasResolvedAt()) {
        if (!getResolvedAt()
            .equals(other.getResolvedAt())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEVICE_NO_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceNo().hashCode();
      hash = (37 * hash) + FAULT_ID_FIELD_NUMBER;
      hash = (53 * hash) + getFaultId();
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp().hashCode();
      }
      if (hasCollectedAt()) {
        hash = (37 * hash) + COLLECTED_AT_FIELD_NUMBER;
        hash = (53 * hash) + getCollectedAt().hashCode();
      }
      if (hasResolvedAt()) {
        hash = (37 * hash) + RESOLVED_AT_FIELD_NUMBER;
        hash = (53 * hash) + getResolvedAt().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Fault.VehicleFaultData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Fault.VehicleFaultData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Fault.VehicleFaultData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Fault.VehicleFaultData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Fault.VehicleFaultData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Fault.VehicleFaultData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Fault.VehicleFaultData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Fault.VehicleFaultData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static Fault.VehicleFaultData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static Fault.VehicleFaultData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Fault.VehicleFaultData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static Fault.VehicleFaultData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Fault.VehicleFaultData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VehicleFaultData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:VehicleFaultData)
        Fault.VehicleFaultDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Fault.internal_static_VehicleFaultData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Fault.internal_static_VehicleFaultData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Fault.VehicleFaultData.class, Fault.VehicleFaultData.Builder.class);
      }

      // Construct using Fault.VehicleFaultData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getTimestampFieldBuilder();
          getCollectedAtFieldBuilder();
          getResolvedAtFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        deviceNo_ = "";
        faultId_ = 0;
        timestamp_ = null;
        if (timestampBuilder_ != null) {
          timestampBuilder_.dispose();
          timestampBuilder_ = null;
        }
        collectedAt_ = null;
        if (collectedAtBuilder_ != null) {
          collectedAtBuilder_.dispose();
          collectedAtBuilder_ = null;
        }
        resolvedAt_ = null;
        if (resolvedAtBuilder_ != null) {
          resolvedAtBuilder_.dispose();
          resolvedAtBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Fault.internal_static_VehicleFaultData_descriptor;
      }

      @java.lang.Override
      public Fault.VehicleFaultData getDefaultInstanceForType() {
        return Fault.VehicleFaultData.getDefaultInstance();
      }

      @java.lang.Override
      public Fault.VehicleFaultData build() {
        Fault.VehicleFaultData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public Fault.VehicleFaultData buildPartial() {
        Fault.VehicleFaultData result = new Fault.VehicleFaultData(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(Fault.VehicleFaultData result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.deviceNo_ = deviceNo_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.faultId_ = faultId_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.timestamp_ = timestampBuilder_ == null
              ? timestamp_
              : timestampBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.collectedAt_ = collectedAtBuilder_ == null
              ? collectedAt_
              : collectedAtBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.resolvedAt_ = resolvedAtBuilder_ == null
              ? resolvedAt_
              : resolvedAtBuilder_.build();
          to_bitField0_ |= 0x00000004;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Fault.VehicleFaultData) {
          return mergeFrom((Fault.VehicleFaultData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Fault.VehicleFaultData other) {
        if (other == Fault.VehicleFaultData.getDefaultInstance()) return this;
        if (!other.getDeviceNo().isEmpty()) {
          deviceNo_ = other.deviceNo_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getFaultId() != 0) {
          setFaultId(other.getFaultId());
        }
        if (other.hasTimestamp()) {
          mergeTimestamp(other.getTimestamp());
        }
        if (other.hasCollectedAt()) {
          mergeCollectedAt(other.getCollectedAt());
        }
        if (other.hasResolvedAt()) {
          mergeResolvedAt(other.getResolvedAt());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                deviceNo_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                faultId_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                input.readMessage(
                    getTimestampFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                input.readMessage(
                    getCollectedAtFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                input.readMessage(
                    getResolvedAtFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object deviceNo_ = "";
      /**
       * <code>string device_no = 1;</code>
       * @return The deviceNo.
       */
      public java.lang.String getDeviceNo() {
        java.lang.Object ref = deviceNo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceNo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string device_no = 1;</code>
       * @return The bytes for deviceNo.
       */
      public com.google.protobuf.ByteString
          getDeviceNoBytes() {
        java.lang.Object ref = deviceNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string device_no = 1;</code>
       * @param value The deviceNo to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceNo(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        deviceNo_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string device_no = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceNo() {
        deviceNo_ = getDefaultInstance().getDeviceNo();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string device_no = 1;</code>
       * @param value The bytes for deviceNo to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        deviceNo_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int faultId_ ;
      /**
       * <code>int32 fault_id = 2;</code>
       * @return The faultId.
       */
      @java.lang.Override
      public int getFaultId() {
        return faultId_;
      }
      /**
       * <code>int32 fault_id = 2;</code>
       * @param value The faultId to set.
       * @return This builder for chaining.
       */
      public Builder setFaultId(int value) {

        faultId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 fault_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearFaultId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        faultId_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp timestamp_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
      /**
       * <code>.google.protobuf.Timestamp timestamp = 3;</code>
       * @return Whether the timestamp field is set.
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 3;</code>
       * @return The timestamp.
       */
      public com.google.protobuf.Timestamp getTimestamp() {
        if (timestampBuilder_ == null) {
          return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
        } else {
          return timestampBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 3;</code>
       */
      public Builder setTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          timestamp_ = value;
        } else {
          timestampBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 3;</code>
       */
      public Builder setTimestamp(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (timestampBuilder_ == null) {
          timestamp_ = builderForValue.build();
        } else {
          timestampBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 3;</code>
       */
      public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            timestamp_ != null &&
            timestamp_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getTimestampBuilder().mergeFrom(value);
          } else {
            timestamp_ = value;
          }
        } else {
          timestampBuilder_.mergeFrom(value);
        }
        if (timestamp_ != null) {
          bitField0_ |= 0x00000004;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 3;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = null;
        if (timestampBuilder_ != null) {
          timestampBuilder_.dispose();
          timestampBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 3;</code>
       */
      public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getTimestampFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 3;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
        if (timestampBuilder_ != null) {
          return timestampBuilder_.getMessageOrBuilder();
        } else {
          return timestamp_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getTimestampFieldBuilder() {
        if (timestampBuilder_ == null) {
          timestampBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getTimestamp(),
                  getParentForChildren(),
                  isClean());
          timestamp_ = null;
        }
        return timestampBuilder_;
      }

      private com.google.protobuf.Timestamp collectedAt_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> collectedAtBuilder_;
      /**
       * <code>.google.protobuf.Timestamp collected_at = 4;</code>
       * @return Whether the collectedAt field is set.
       */
      public boolean hasCollectedAt() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp collected_at = 4;</code>
       * @return The collectedAt.
       */
      public com.google.protobuf.Timestamp getCollectedAt() {
        if (collectedAtBuilder_ == null) {
          return collectedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : collectedAt_;
        } else {
          return collectedAtBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp collected_at = 4;</code>
       */
      public Builder setCollectedAt(com.google.protobuf.Timestamp value) {
        if (collectedAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          collectedAt_ = value;
        } else {
          collectedAtBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp collected_at = 4;</code>
       */
      public Builder setCollectedAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (collectedAtBuilder_ == null) {
          collectedAt_ = builderForValue.build();
        } else {
          collectedAtBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp collected_at = 4;</code>
       */
      public Builder mergeCollectedAt(com.google.protobuf.Timestamp value) {
        if (collectedAtBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            collectedAt_ != null &&
            collectedAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getCollectedAtBuilder().mergeFrom(value);
          } else {
            collectedAt_ = value;
          }
        } else {
          collectedAtBuilder_.mergeFrom(value);
        }
        if (collectedAt_ != null) {
          bitField0_ |= 0x00000008;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp collected_at = 4;</code>
       */
      public Builder clearCollectedAt() {
        bitField0_ = (bitField0_ & ~0x00000008);
        collectedAt_ = null;
        if (collectedAtBuilder_ != null) {
          collectedAtBuilder_.dispose();
          collectedAtBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp collected_at = 4;</code>
       */
      public com.google.protobuf.Timestamp.Builder getCollectedAtBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getCollectedAtFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp collected_at = 4;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getCollectedAtOrBuilder() {
        if (collectedAtBuilder_ != null) {
          return collectedAtBuilder_.getMessageOrBuilder();
        } else {
          return collectedAt_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : collectedAt_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp collected_at = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getCollectedAtFieldBuilder() {
        if (collectedAtBuilder_ == null) {
          collectedAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getCollectedAt(),
                  getParentForChildren(),
                  isClean());
          collectedAt_ = null;
        }
        return collectedAtBuilder_;
      }

      private com.google.protobuf.Timestamp resolvedAt_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> resolvedAtBuilder_;
      /**
       * <code>.google.protobuf.Timestamp resolved_at = 5;</code>
       * @return Whether the resolvedAt field is set.
       */
      public boolean hasResolvedAt() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp resolved_at = 5;</code>
       * @return The resolvedAt.
       */
      public com.google.protobuf.Timestamp getResolvedAt() {
        if (resolvedAtBuilder_ == null) {
          return resolvedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : resolvedAt_;
        } else {
          return resolvedAtBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp resolved_at = 5;</code>
       */
      public Builder setResolvedAt(com.google.protobuf.Timestamp value) {
        if (resolvedAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          resolvedAt_ = value;
        } else {
          resolvedAtBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp resolved_at = 5;</code>
       */
      public Builder setResolvedAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (resolvedAtBuilder_ == null) {
          resolvedAt_ = builderForValue.build();
        } else {
          resolvedAtBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp resolved_at = 5;</code>
       */
      public Builder mergeResolvedAt(com.google.protobuf.Timestamp value) {
        if (resolvedAtBuilder_ == null) {
          if (((bitField0_ & 0x00000010) != 0) &&
            resolvedAt_ != null &&
            resolvedAt_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getResolvedAtBuilder().mergeFrom(value);
          } else {
            resolvedAt_ = value;
          }
        } else {
          resolvedAtBuilder_.mergeFrom(value);
        }
        if (resolvedAt_ != null) {
          bitField0_ |= 0x00000010;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp resolved_at = 5;</code>
       */
      public Builder clearResolvedAt() {
        bitField0_ = (bitField0_ & ~0x00000010);
        resolvedAt_ = null;
        if (resolvedAtBuilder_ != null) {
          resolvedAtBuilder_.dispose();
          resolvedAtBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp resolved_at = 5;</code>
       */
      public com.google.protobuf.Timestamp.Builder getResolvedAtBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getResolvedAtFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp resolved_at = 5;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getResolvedAtOrBuilder() {
        if (resolvedAtBuilder_ != null) {
          return resolvedAtBuilder_.getMessageOrBuilder();
        } else {
          return resolvedAt_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : resolvedAt_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp resolved_at = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getResolvedAtFieldBuilder() {
        if (resolvedAtBuilder_ == null) {
          resolvedAtBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getResolvedAt(),
                  getParentForChildren(),
                  isClean());
          resolvedAt_ = null;
        }
        return resolvedAtBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:VehicleFaultData)
    }

    // @@protoc_insertion_point(class_scope:VehicleFaultData)
    private static final Fault.VehicleFaultData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Fault.VehicleFaultData();
    }

    public static Fault.VehicleFaultData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VehicleFaultData>
        PARSER = new com.google.protobuf.AbstractParser<VehicleFaultData>() {
      @java.lang.Override
      public VehicleFaultData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<VehicleFaultData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VehicleFaultData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public Fault.VehicleFaultData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VehicleFaultData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_VehicleFaultData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013fault.proto\032\037google/protobuf/timestamp" +
      ".proto\"\311\001\n\020VehicleFaultData\022\021\n\tdevice_no" +
      "\030\001 \001(\t\022\020\n\010fault_id\030\002 \001(\005\022-\n\ttimestamp\030\003 " +
      "\001(\0132\032.google.protobuf.Timestamp\0220\n\014colle" +
      "cted_at\030\004 \001(\0132\032.google.protobuf.Timestam" +
      "p\022/\n\013resolved_at\030\005 \001(\0132\032.google.protobuf" +
      ".Timestampb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_VehicleFaultData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_VehicleFaultData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_VehicleFaultData_descriptor,
        new java.lang.String[] { "DeviceNo", "FaultId", "Timestamp", "CollectedAt", "ResolvedAt", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
