// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: payloadData.proto
// Protobuf Java Version: 4.29.0-rc1

package com.veeron.lambdaforaws.payloadData;

public final class PayloadData {
  private PayloadData() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 29,
      /* patch= */ 0,
      /* suffix= */ "-rc1",
      PayloadData.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GPSOrBuilder extends
      // @@protoc_insertion_point(interface_extends:GPS)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double latitude = 1;</code>
     * @return The latitude.
     */
    double getLatitude();

    /**
     * <code>double longitude = 2;</code>
     * @return The longitude.
     */
    double getLongitude();

    /**
     * <code>float altitude = 3;</code>
     * @return The altitude.
     */
    float getAltitude();
  }
  /**
   * Protobuf type {@code GPS}
   */
  public static final class GPS extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:GPS)
      GPSOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 0,
        /* suffix= */ "-rc1",
        GPS.class.getName());
    }
    // Use GPS.newBuilder() to construct.
    private GPS(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GPS() {
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PayloadData.internal_static_GPS_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PayloadData.internal_static_GPS_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PayloadData.GPS.class, PayloadData.GPS.Builder.class);
    }

    public static final int LATITUDE_FIELD_NUMBER = 1;
    private double latitude_ = 0D;
    /**
     * <code>double latitude = 1;</code>
     * @return The latitude.
     */
    @java.lang.Override
    public double getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private double longitude_ = 0D;
    /**
     * <code>double longitude = 2;</code>
     * @return The longitude.
     */
    @java.lang.Override
    public double getLongitude() {
      return longitude_;
    }

    public static final int ALTITUDE_FIELD_NUMBER = 3;
    private float altitude_ = 0F;
    /**
     * <code>float altitude = 3;</code>
     * @return The altitude.
     */
    @java.lang.Override
    public float getAltitude() {
      return altitude_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (java.lang.Double.doubleToRawLongBits(latitude_) != 0) {
        output.writeDouble(1, latitude_);
      }
      if (java.lang.Double.doubleToRawLongBits(longitude_) != 0) {
        output.writeDouble(2, longitude_);
      }
      if (java.lang.Float.floatToRawIntBits(altitude_) != 0) {
        output.writeFloat(3, altitude_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (java.lang.Double.doubleToRawLongBits(latitude_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, latitude_);
      }
      if (java.lang.Double.doubleToRawLongBits(longitude_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, longitude_);
      }
      if (java.lang.Float.floatToRawIntBits(altitude_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, altitude_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PayloadData.GPS)) {
        return super.equals(obj);
      }
      PayloadData.GPS other = (PayloadData.GPS) obj;

      if (java.lang.Double.doubleToLongBits(getLatitude())
          != java.lang.Double.doubleToLongBits(
              other.getLatitude())) return false;
      if (java.lang.Double.doubleToLongBits(getLongitude())
          != java.lang.Double.doubleToLongBits(
              other.getLongitude())) return false;
      if (java.lang.Float.floatToIntBits(getAltitude())
          != java.lang.Float.floatToIntBits(
              other.getAltitude())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLatitude()));
      hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getLongitude()));
      hash = (37 * hash) + ALTITUDE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getAltitude());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PayloadData.GPS parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PayloadData.GPS parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PayloadData.GPS parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PayloadData.GPS parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PayloadData.GPS parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PayloadData.GPS parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PayloadData.GPS parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static PayloadData.GPS parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static PayloadData.GPS parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static PayloadData.GPS parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PayloadData.GPS parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static PayloadData.GPS parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PayloadData.GPS prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code GPS}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:GPS)
        PayloadData.GPSOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PayloadData.internal_static_GPS_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PayloadData.internal_static_GPS_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PayloadData.GPS.class, PayloadData.GPS.Builder.class);
      }

      // Construct using PayloadData.GPS.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        latitude_ = 0D;
        longitude_ = 0D;
        altitude_ = 0F;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PayloadData.internal_static_GPS_descriptor;
      }

      @java.lang.Override
      public PayloadData.GPS getDefaultInstanceForType() {
        return PayloadData.GPS.getDefaultInstance();
      }

      @java.lang.Override
      public PayloadData.GPS build() {
        PayloadData.GPS result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public PayloadData.GPS buildPartial() {
        PayloadData.GPS result = new PayloadData.GPS(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(PayloadData.GPS result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.latitude_ = latitude_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.longitude_ = longitude_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.altitude_ = altitude_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PayloadData.GPS) {
          return mergeFrom((PayloadData.GPS)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PayloadData.GPS other) {
        if (other == PayloadData.GPS.getDefaultInstance()) return this;
        if (other.getLatitude() != 0D) {
          setLatitude(other.getLatitude());
        }
        if (other.getLongitude() != 0D) {
          setLongitude(other.getLongitude());
        }
        if (other.getAltitude() != 0F) {
          setAltitude(other.getAltitude());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 9: {
                latitude_ = input.readDouble();
                bitField0_ |= 0x00000001;
                break;
              } // case 9
              case 17: {
                longitude_ = input.readDouble();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              case 29: {
                altitude_ = input.readFloat();
                bitField0_ |= 0x00000004;
                break;
              } // case 29
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private double latitude_ ;
      /**
       * <code>double latitude = 1;</code>
       * @return The latitude.
       */
      @java.lang.Override
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>double latitude = 1;</code>
       * @param value The latitude to set.
       * @return This builder for chaining.
       */
      public Builder setLatitude(double value) {

        latitude_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>double latitude = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000001);
        latitude_ = 0D;
        onChanged();
        return this;
      }

      private double longitude_ ;
      /**
       * <code>double longitude = 2;</code>
       * @return The longitude.
       */
      @java.lang.Override
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>double longitude = 2;</code>
       * @param value The longitude to set.
       * @return This builder for chaining.
       */
      public Builder setLongitude(double value) {

        longitude_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>double longitude = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000002);
        longitude_ = 0D;
        onChanged();
        return this;
      }

      private float altitude_ ;
      /**
       * <code>float altitude = 3;</code>
       * @return The altitude.
       */
      @java.lang.Override
      public float getAltitude() {
        return altitude_;
      }
      /**
       * <code>float altitude = 3;</code>
       * @param value The altitude to set.
       * @return This builder for chaining.
       */
      public Builder setAltitude(float value) {

        altitude_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>float altitude = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAltitude() {
        bitField0_ = (bitField0_ & ~0x00000004);
        altitude_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:GPS)
    }

    // @@protoc_insertion_point(class_scope:GPS)
    private static final PayloadData.GPS DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PayloadData.GPS();
    }

    public static PayloadData.GPS getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GPS>
        PARSER = new com.google.protobuf.AbstractParser<GPS>() {
      @java.lang.Override
      public GPS parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<GPS> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GPS> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public PayloadData.GPS getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VehicleDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VehicleData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string device_no = 1;</code>
     * @return The deviceNo.
     */
    java.lang.String getDeviceNo();
    /**
     * <code>string device_no = 1;</code>
     * @return The bytes for deviceNo.
     */
    com.google.protobuf.ByteString
        getDeviceNoBytes();

    /**
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     * @return Whether the timestamp field is set.
     */
    boolean hasTimestamp();
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     * @return The timestamp.
     */
    com.google.protobuf.Timestamp getTimestamp();
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     */
    com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder();

    /**
     * <code>.GPS gps = 3;</code>
     * @return Whether the gps field is set.
     */
    boolean hasGps();
    /**
     * <code>.GPS gps = 3;</code>
     * @return The gps.
     */
    PayloadData.GPS getGps();
    /**
     * <code>.GPS gps = 3;</code>
     */
    PayloadData.GPSOrBuilder getGpsOrBuilder();

    /**
     * <code>optional float battery_voltage = 4;</code>
     * @return Whether the batteryVoltage field is set.
     */
    boolean hasBatteryVoltage();
    /**
     * <code>optional float battery_voltage = 4;</code>
     * @return The batteryVoltage.
     */
    float getBatteryVoltage();

    /**
     * <code>optional float battery_current = 5;</code>
     * @return Whether the batteryCurrent field is set.
     */
    boolean hasBatteryCurrent();
    /**
     * <code>optional float battery_current = 5;</code>
     * @return The batteryCurrent.
     */
    float getBatteryCurrent();

    /**
     * <code>optional float vehicle_speed = 6;</code>
     * @return Whether the vehicleSpeed field is set.
     */
    boolean hasVehicleSpeed();
    /**
     * <code>optional float vehicle_speed = 6;</code>
     * @return The vehicleSpeed.
     */
    float getVehicleSpeed();

    /**
     * <code>optional .VehicleData.Gear gear = 7;</code>
     * @return Whether the gear field is set.
     */
    boolean hasGear();
    /**
     * <code>optional .VehicleData.Gear gear = 7;</code>
     * @return The enum numeric value on the wire for gear.
     */
    int getGearValue();
    /**
     * <code>optional .VehicleData.Gear gear = 7;</code>
     * @return The gear.
     */
    PayloadData.VehicleData.Gear getGear();
  }
  /**
   * Protobuf type {@code VehicleData}
   */
  public static final class VehicleData extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:VehicleData)
      VehicleDataOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 29,
        /* patch= */ 0,
        /* suffix= */ "-rc1",
        VehicleData.class.getName());
    }
    // Use VehicleData.newBuilder() to construct.
    private VehicleData(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private VehicleData() {
      deviceNo_ = "";
      gear_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return PayloadData.internal_static_VehicleData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return PayloadData.internal_static_VehicleData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              PayloadData.VehicleData.class, PayloadData.VehicleData.Builder.class);
    }

    /**
     * Protobuf enum {@code VehicleData.Gear}
     */
    public enum Gear
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>PARKING = 0;</code>
       */
      PARKING(0),
      /**
       * <code>DRIVE_MEDIUM = 1;</code>
       */
      DRIVE_MEDIUM(1),
      /**
       * <code>DRIVE_LOW = 2;</code>
       */
      DRIVE_LOW(2),
      /**
       * <code>DRIVE_HIGH = 3;</code>
       */
      DRIVE_HIGH(3),
      /**
       * <code>REVERSE = 4;</code>
       */
      REVERSE(4),
      UNRECOGNIZED(-1),
      ;

      static {
        com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
          com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
          /* major= */ 4,
          /* minor= */ 29,
          /* patch= */ 0,
          /* suffix= */ "-rc1",
          Gear.class.getName());
      }
      /**
       * <code>PARKING = 0;</code>
       */
      public static final int PARKING_VALUE = 0;
      /**
       * <code>DRIVE_MEDIUM = 1;</code>
       */
      public static final int DRIVE_MEDIUM_VALUE = 1;
      /**
       * <code>DRIVE_LOW = 2;</code>
       */
      public static final int DRIVE_LOW_VALUE = 2;
      /**
       * <code>DRIVE_HIGH = 3;</code>
       */
      public static final int DRIVE_HIGH_VALUE = 3;
      /**
       * <code>REVERSE = 4;</code>
       */
      public static final int REVERSE_VALUE = 4;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Gear valueOf(int value) {
        return forNumber(value);
      }

      /**
       * @param value The numeric wire value of the corresponding enum entry.
       * @return The enum associated with the given numeric wire value.
       */
      public static Gear forNumber(int value) {
        switch (value) {
          case 0: return PARKING;
          case 1: return DRIVE_MEDIUM;
          case 2: return DRIVE_LOW;
          case 3: return DRIVE_HIGH;
          case 4: return REVERSE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Gear>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Gear> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Gear>() {
              public Gear findValueByNumber(int number) {
                return Gear.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalStateException(
              "Can't get the descriptor of an unrecognized enum value.");
        }
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return PayloadData.VehicleData.getDescriptor().getEnumTypes().get(0);
      }

      private static final Gear[] VALUES = values();

      public static Gear valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Gear(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:VehicleData.Gear)
    }

    private int bitField0_;
    public static final int DEVICE_NO_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object deviceNo_ = "";
    /**
     * <code>string device_no = 1;</code>
     * @return The deviceNo.
     */
    @java.lang.Override
    public java.lang.String getDeviceNo() {
      java.lang.Object ref = deviceNo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceNo_ = s;
        return s;
      }
    }
    /**
     * <code>string device_no = 1;</code>
     * @return The bytes for deviceNo.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDeviceNoBytes() {
      java.lang.Object ref = deviceNo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceNo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private com.google.protobuf.Timestamp timestamp_;
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     * @return Whether the timestamp field is set.
     */
    @java.lang.Override
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getTimestamp() {
      return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
    }
    /**
     * <code>.google.protobuf.Timestamp timestamp = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
      return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
    }

    public static final int GPS_FIELD_NUMBER = 3;
    private PayloadData.GPS gps_;
    /**
     * <code>.GPS gps = 3;</code>
     * @return Whether the gps field is set.
     */
    @java.lang.Override
    public boolean hasGps() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.GPS gps = 3;</code>
     * @return The gps.
     */
    @java.lang.Override
    public PayloadData.GPS getGps() {
      return gps_ == null ? PayloadData.GPS.getDefaultInstance() : gps_;
    }
    /**
     * <code>.GPS gps = 3;</code>
     */
    @java.lang.Override
    public PayloadData.GPSOrBuilder getGpsOrBuilder() {
      return gps_ == null ? PayloadData.GPS.getDefaultInstance() : gps_;
    }

    public static final int BATTERY_VOLTAGE_FIELD_NUMBER = 4;
    private float batteryVoltage_ = 0F;
    /**
     * <code>optional float battery_voltage = 4;</code>
     * @return Whether the batteryVoltage field is set.
     */
    @java.lang.Override
    public boolean hasBatteryVoltage() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional float battery_voltage = 4;</code>
     * @return The batteryVoltage.
     */
    @java.lang.Override
    public float getBatteryVoltage() {
      return batteryVoltage_;
    }

    public static final int BATTERY_CURRENT_FIELD_NUMBER = 5;
    private float batteryCurrent_ = 0F;
    /**
     * <code>optional float battery_current = 5;</code>
     * @return Whether the batteryCurrent field is set.
     */
    @java.lang.Override
    public boolean hasBatteryCurrent() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>optional float battery_current = 5;</code>
     * @return The batteryCurrent.
     */
    @java.lang.Override
    public float getBatteryCurrent() {
      return batteryCurrent_;
    }

    public static final int VEHICLE_SPEED_FIELD_NUMBER = 6;
    private float vehicleSpeed_ = 0F;
    /**
     * <code>optional float vehicle_speed = 6;</code>
     * @return Whether the vehicleSpeed field is set.
     */
    @java.lang.Override
    public boolean hasVehicleSpeed() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>optional float vehicle_speed = 6;</code>
     * @return The vehicleSpeed.
     */
    @java.lang.Override
    public float getVehicleSpeed() {
      return vehicleSpeed_;
    }

    public static final int GEAR_FIELD_NUMBER = 7;
    private int gear_ = 0;
    /**
     * <code>optional .VehicleData.Gear gear = 7;</code>
     * @return Whether the gear field is set.
     */
    @java.lang.Override public boolean hasGear() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional .VehicleData.Gear gear = 7;</code>
     * @return The enum numeric value on the wire for gear.
     */
    @java.lang.Override public int getGearValue() {
      return gear_;
    }
    /**
     * <code>optional .VehicleData.Gear gear = 7;</code>
     * @return The gear.
     */
    @java.lang.Override public PayloadData.VehicleData.Gear getGear() {
      PayloadData.VehicleData.Gear result = PayloadData.VehicleData.Gear.forNumber(gear_);
      return result == null ? PayloadData.VehicleData.Gear.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deviceNo_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, deviceNo_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(2, getTimestamp());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeMessage(3, getGps());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeFloat(4, batteryVoltage_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeFloat(5, batteryCurrent_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeFloat(6, vehicleSpeed_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeEnum(7, gear_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(deviceNo_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, deviceNo_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getTimestamp());
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getGps());
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, batteryVoltage_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, batteryCurrent_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, vehicleSpeed_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(7, gear_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof PayloadData.VehicleData)) {
        return super.equals(obj);
      }
      PayloadData.VehicleData other = (PayloadData.VehicleData) obj;

      if (!getDeviceNo()
          .equals(other.getDeviceNo())) return false;
      if (hasTimestamp() != other.hasTimestamp()) return false;
      if (hasTimestamp()) {
        if (!getTimestamp()
            .equals(other.getTimestamp())) return false;
      }
      if (hasGps() != other.hasGps()) return false;
      if (hasGps()) {
        if (!getGps()
            .equals(other.getGps())) return false;
      }
      if (hasBatteryVoltage() != other.hasBatteryVoltage()) return false;
      if (hasBatteryVoltage()) {
        if (java.lang.Float.floatToIntBits(getBatteryVoltage())
            != java.lang.Float.floatToIntBits(
                other.getBatteryVoltage())) return false;
      }
      if (hasBatteryCurrent() != other.hasBatteryCurrent()) return false;
      if (hasBatteryCurrent()) {
        if (java.lang.Float.floatToIntBits(getBatteryCurrent())
            != java.lang.Float.floatToIntBits(
                other.getBatteryCurrent())) return false;
      }
      if (hasVehicleSpeed() != other.hasVehicleSpeed()) return false;
      if (hasVehicleSpeed()) {
        if (java.lang.Float.floatToIntBits(getVehicleSpeed())
            != java.lang.Float.floatToIntBits(
                other.getVehicleSpeed())) return false;
      }
      if (hasGear() != other.hasGear()) return false;
      if (hasGear()) {
        if (gear_ != other.gear_) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DEVICE_NO_FIELD_NUMBER;
      hash = (53 * hash) + getDeviceNo().hashCode();
      if (hasTimestamp()) {
        hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getTimestamp().hashCode();
      }
      if (hasGps()) {
        hash = (37 * hash) + GPS_FIELD_NUMBER;
        hash = (53 * hash) + getGps().hashCode();
      }
      if (hasBatteryVoltage()) {
        hash = (37 * hash) + BATTERY_VOLTAGE_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getBatteryVoltage());
      }
      if (hasBatteryCurrent()) {
        hash = (37 * hash) + BATTERY_CURRENT_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getBatteryCurrent());
      }
      if (hasVehicleSpeed()) {
        hash = (37 * hash) + VEHICLE_SPEED_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getVehicleSpeed());
      }
      if (hasGear()) {
        hash = (37 * hash) + GEAR_FIELD_NUMBER;
        hash = (53 * hash) + gear_;
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static PayloadData.VehicleData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PayloadData.VehicleData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PayloadData.VehicleData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PayloadData.VehicleData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PayloadData.VehicleData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static PayloadData.VehicleData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static PayloadData.VehicleData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static PayloadData.VehicleData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static PayloadData.VehicleData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static PayloadData.VehicleData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static PayloadData.VehicleData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static PayloadData.VehicleData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(PayloadData.VehicleData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VehicleData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:VehicleData)
        PayloadData.VehicleDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return PayloadData.internal_static_VehicleData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return PayloadData.internal_static_VehicleData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                PayloadData.VehicleData.class, PayloadData.VehicleData.Builder.class);
      }

      // Construct using PayloadData.VehicleData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getTimestampFieldBuilder();
          getGpsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        deviceNo_ = "";
        timestamp_ = null;
        if (timestampBuilder_ != null) {
          timestampBuilder_.dispose();
          timestampBuilder_ = null;
        }
        gps_ = null;
        if (gpsBuilder_ != null) {
          gpsBuilder_.dispose();
          gpsBuilder_ = null;
        }
        batteryVoltage_ = 0F;
        batteryCurrent_ = 0F;
        vehicleSpeed_ = 0F;
        gear_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return PayloadData.internal_static_VehicleData_descriptor;
      }

      @java.lang.Override
      public PayloadData.VehicleData getDefaultInstanceForType() {
        return PayloadData.VehicleData.getDefaultInstance();
      }

      @java.lang.Override
      public PayloadData.VehicleData build() {
        PayloadData.VehicleData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public PayloadData.VehicleData buildPartial() {
        PayloadData.VehicleData result = new PayloadData.VehicleData(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(PayloadData.VehicleData result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.deviceNo_ = deviceNo_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.timestamp_ = timestampBuilder_ == null
              ? timestamp_
              : timestampBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.gps_ = gpsBuilder_ == null
              ? gps_
              : gpsBuilder_.build();
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.batteryVoltage_ = batteryVoltage_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.batteryCurrent_ = batteryCurrent_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.vehicleSpeed_ = vehicleSpeed_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.gear_ = gear_;
          to_bitField0_ |= 0x00000020;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof PayloadData.VehicleData) {
          return mergeFrom((PayloadData.VehicleData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(PayloadData.VehicleData other) {
        if (other == PayloadData.VehicleData.getDefaultInstance()) return this;
        if (!other.getDeviceNo().isEmpty()) {
          deviceNo_ = other.deviceNo_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasTimestamp()) {
          mergeTimestamp(other.getTimestamp());
        }
        if (other.hasGps()) {
          mergeGps(other.getGps());
        }
        if (other.hasBatteryVoltage()) {
          setBatteryVoltage(other.getBatteryVoltage());
        }
        if (other.hasBatteryCurrent()) {
          setBatteryCurrent(other.getBatteryCurrent());
        }
        if (other.hasVehicleSpeed()) {
          setVehicleSpeed(other.getVehicleSpeed());
        }
        if (other.hasGear()) {
          setGear(other.getGear());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                deviceNo_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                input.readMessage(
                    getTimestampFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                input.readMessage(
                    getGpsFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 37: {
                batteryVoltage_ = input.readFloat();
                bitField0_ |= 0x00000008;
                break;
              } // case 37
              case 45: {
                batteryCurrent_ = input.readFloat();
                bitField0_ |= 0x00000010;
                break;
              } // case 45
              case 53: {
                vehicleSpeed_ = input.readFloat();
                bitField0_ |= 0x00000020;
                break;
              } // case 53
              case 56: {
                gear_ = input.readEnum();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object deviceNo_ = "";
      /**
       * <code>string device_no = 1;</code>
       * @return The deviceNo.
       */
      public java.lang.String getDeviceNo() {
        java.lang.Object ref = deviceNo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          deviceNo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string device_no = 1;</code>
       * @return The bytes for deviceNo.
       */
      public com.google.protobuf.ByteString
          getDeviceNoBytes() {
        java.lang.Object ref = deviceNo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deviceNo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string device_no = 1;</code>
       * @param value The deviceNo to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceNo(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        deviceNo_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string device_no = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDeviceNo() {
        deviceNo_ = getDefaultInstance().getDeviceNo();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string device_no = 1;</code>
       * @param value The bytes for deviceNo to set.
       * @return This builder for chaining.
       */
      public Builder setDeviceNoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        deviceNo_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp timestamp_;
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> timestampBuilder_;
      /**
       * <code>.google.protobuf.Timestamp timestamp = 2;</code>
       * @return Whether the timestamp field is set.
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 2;</code>
       * @return The timestamp.
       */
      public com.google.protobuf.Timestamp getTimestamp() {
        if (timestampBuilder_ == null) {
          return timestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
        } else {
          return timestampBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 2;</code>
       */
      public Builder setTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          timestamp_ = value;
        } else {
          timestampBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 2;</code>
       */
      public Builder setTimestamp(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (timestampBuilder_ == null) {
          timestamp_ = builderForValue.build();
        } else {
          timestampBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 2;</code>
       */
      public Builder mergeTimestamp(com.google.protobuf.Timestamp value) {
        if (timestampBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0) &&
            timestamp_ != null &&
            timestamp_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
            getTimestampBuilder().mergeFrom(value);
          } else {
            timestamp_ = value;
          }
        } else {
          timestampBuilder_.mergeFrom(value);
        }
        if (timestamp_ != null) {
          bitField0_ |= 0x00000002;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 2;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = null;
        if (timestampBuilder_ != null) {
          timestampBuilder_.dispose();
          timestampBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 2;</code>
       */
      public com.google.protobuf.Timestamp.Builder getTimestampBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getTimestampFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 2;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getTimestampOrBuilder() {
        if (timestampBuilder_ != null) {
          return timestampBuilder_.getMessageOrBuilder();
        } else {
          return timestamp_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : timestamp_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp timestamp = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getTimestampFieldBuilder() {
        if (timestampBuilder_ == null) {
          timestampBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getTimestamp(),
                  getParentForChildren(),
                  isClean());
          timestamp_ = null;
        }
        return timestampBuilder_;
      }

      private PayloadData.GPS gps_;
      private com.google.protobuf.SingleFieldBuilder<
          PayloadData.GPS, PayloadData.GPS.Builder, PayloadData.GPSOrBuilder> gpsBuilder_;
      /**
       * <code>.GPS gps = 3;</code>
       * @return Whether the gps field is set.
       */
      public boolean hasGps() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.GPS gps = 3;</code>
       * @return The gps.
       */
      public PayloadData.GPS getGps() {
        if (gpsBuilder_ == null) {
          return gps_ == null ? PayloadData.GPS.getDefaultInstance() : gps_;
        } else {
          return gpsBuilder_.getMessage();
        }
      }
      /**
       * <code>.GPS gps = 3;</code>
       */
      public Builder setGps(PayloadData.GPS value) {
        if (gpsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          gps_ = value;
        } else {
          gpsBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.GPS gps = 3;</code>
       */
      public Builder setGps(
          PayloadData.GPS.Builder builderForValue) {
        if (gpsBuilder_ == null) {
          gps_ = builderForValue.build();
        } else {
          gpsBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.GPS gps = 3;</code>
       */
      public Builder mergeGps(PayloadData.GPS value) {
        if (gpsBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            gps_ != null &&
            gps_ != PayloadData.GPS.getDefaultInstance()) {
            getGpsBuilder().mergeFrom(value);
          } else {
            gps_ = value;
          }
        } else {
          gpsBuilder_.mergeFrom(value);
        }
        if (gps_ != null) {
          bitField0_ |= 0x00000004;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.GPS gps = 3;</code>
       */
      public Builder clearGps() {
        bitField0_ = (bitField0_ & ~0x00000004);
        gps_ = null;
        if (gpsBuilder_ != null) {
          gpsBuilder_.dispose();
          gpsBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.GPS gps = 3;</code>
       */
      public PayloadData.GPS.Builder getGpsBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getGpsFieldBuilder().getBuilder();
      }
      /**
       * <code>.GPS gps = 3;</code>
       */
      public PayloadData.GPSOrBuilder getGpsOrBuilder() {
        if (gpsBuilder_ != null) {
          return gpsBuilder_.getMessageOrBuilder();
        } else {
          return gps_ == null ?
              PayloadData.GPS.getDefaultInstance() : gps_;
        }
      }
      /**
       * <code>.GPS gps = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          PayloadData.GPS, PayloadData.GPS.Builder, PayloadData.GPSOrBuilder> 
          getGpsFieldBuilder() {
        if (gpsBuilder_ == null) {
          gpsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              PayloadData.GPS, PayloadData.GPS.Builder, PayloadData.GPSOrBuilder>(
                  getGps(),
                  getParentForChildren(),
                  isClean());
          gps_ = null;
        }
        return gpsBuilder_;
      }

      private float batteryVoltage_ ;
      /**
       * <code>optional float battery_voltage = 4;</code>
       * @return Whether the batteryVoltage field is set.
       */
      @java.lang.Override
      public boolean hasBatteryVoltage() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>optional float battery_voltage = 4;</code>
       * @return The batteryVoltage.
       */
      @java.lang.Override
      public float getBatteryVoltage() {
        return batteryVoltage_;
      }
      /**
       * <code>optional float battery_voltage = 4;</code>
       * @param value The batteryVoltage to set.
       * @return This builder for chaining.
       */
      public Builder setBatteryVoltage(float value) {

        batteryVoltage_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>optional float battery_voltage = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearBatteryVoltage() {
        bitField0_ = (bitField0_ & ~0x00000008);
        batteryVoltage_ = 0F;
        onChanged();
        return this;
      }

      private float batteryCurrent_ ;
      /**
       * <code>optional float battery_current = 5;</code>
       * @return Whether the batteryCurrent field is set.
       */
      @java.lang.Override
      public boolean hasBatteryCurrent() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional float battery_current = 5;</code>
       * @return The batteryCurrent.
       */
      @java.lang.Override
      public float getBatteryCurrent() {
        return batteryCurrent_;
      }
      /**
       * <code>optional float battery_current = 5;</code>
       * @param value The batteryCurrent to set.
       * @return This builder for chaining.
       */
      public Builder setBatteryCurrent(float value) {

        batteryCurrent_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional float battery_current = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearBatteryCurrent() {
        bitField0_ = (bitField0_ & ~0x00000010);
        batteryCurrent_ = 0F;
        onChanged();
        return this;
      }

      private float vehicleSpeed_ ;
      /**
       * <code>optional float vehicle_speed = 6;</code>
       * @return Whether the vehicleSpeed field is set.
       */
      @java.lang.Override
      public boolean hasVehicleSpeed() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional float vehicle_speed = 6;</code>
       * @return The vehicleSpeed.
       */
      @java.lang.Override
      public float getVehicleSpeed() {
        return vehicleSpeed_;
      }
      /**
       * <code>optional float vehicle_speed = 6;</code>
       * @param value The vehicleSpeed to set.
       * @return This builder for chaining.
       */
      public Builder setVehicleSpeed(float value) {

        vehicleSpeed_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional float vehicle_speed = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearVehicleSpeed() {
        bitField0_ = (bitField0_ & ~0x00000020);
        vehicleSpeed_ = 0F;
        onChanged();
        return this;
      }

      private int gear_ = 0;
      /**
       * <code>optional .VehicleData.Gear gear = 7;</code>
       * @return Whether the gear field is set.
       */
      @java.lang.Override public boolean hasGear() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>optional .VehicleData.Gear gear = 7;</code>
       * @return The enum numeric value on the wire for gear.
       */
      @java.lang.Override public int getGearValue() {
        return gear_;
      }
      /**
       * <code>optional .VehicleData.Gear gear = 7;</code>
       * @param value The enum numeric value on the wire for gear to set.
       * @return This builder for chaining.
       */
      public Builder setGearValue(int value) {
        gear_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>optional .VehicleData.Gear gear = 7;</code>
       * @return The gear.
       */
      @java.lang.Override
      public PayloadData.VehicleData.Gear getGear() {
        PayloadData.VehicleData.Gear result = PayloadData.VehicleData.Gear.forNumber(gear_);
        return result == null ? PayloadData.VehicleData.Gear.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .VehicleData.Gear gear = 7;</code>
       * @param value The gear to set.
       * @return This builder for chaining.
       */
      public Builder setGear(PayloadData.VehicleData.Gear value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000040;
        gear_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .VehicleData.Gear gear = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearGear() {
        bitField0_ = (bitField0_ & ~0x00000040);
        gear_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:VehicleData)
    }

    // @@protoc_insertion_point(class_scope:VehicleData)
    private static final PayloadData.VehicleData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PayloadData.VehicleData();
    }

    public static PayloadData.VehicleData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VehicleData>
        PARSER = new com.google.protobuf.AbstractParser<VehicleData>() {
      @java.lang.Override
      public VehicleData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<VehicleData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VehicleData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public PayloadData.VehicleData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GPS_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_GPS_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VehicleData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_VehicleData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021payloadData.proto\032\037google/protobuf/tim" +
      "estamp.proto\"<\n\003GPS\022\020\n\010latitude\030\001 \001(\001\022\021\n" +
      "\tlongitude\030\002 \001(\001\022\020\n\010altitude\030\003 \001(\002\"\366\002\n\013V" +
      "ehicleData\022\021\n\tdevice_no\030\001 \001(\t\022-\n\ttimesta" +
      "mp\030\002 \001(\0132\032.google.protobuf.Timestamp\022\021\n\003" +
      "gps\030\003 \001(\0132\004.GPS\022\034\n\017battery_voltage\030\004 \001(\002" +
      "H\000\210\001\001\022\034\n\017battery_current\030\005 \001(\002H\001\210\001\001\022\032\n\rv" +
      "ehicle_speed\030\006 \001(\002H\002\210\001\001\022$\n\004gear\030\007 \001(\0162\021." +
      "VehicleData.GearH\003\210\001\001\"Q\n\004Gear\022\013\n\007PARKING" +
      "\020\000\022\020\n\014DRIVE_MEDIUM\020\001\022\r\n\tDRIVE_LOW\020\002\022\016\n\nD" +
      "RIVE_HIGH\020\003\022\013\n\007REVERSE\020\004B\022\n\020_battery_vol" +
      "tageB\022\n\020_battery_currentB\020\n\016_vehicle_spe" +
      "edB\007\n\005_gearb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_GPS_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GPS_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_GPS_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", "Altitude", });
    internal_static_VehicleData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_VehicleData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_VehicleData_descriptor,
        new java.lang.String[] { "DeviceNo", "Timestamp", "Gps", "BatteryVoltage", "BatteryCurrent", "VehicleSpeed", "Gear", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
